/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agecalculate;

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double res, num;
    int value;
    
    public Calculator() {
        initComponents();
        jRadioButton1.setEnabled(false);
    }
    
    public void arithmeticOperation()
    {
        switch(value)
        {
            case 1:
                res = num + Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(res));
                break;
            case 2:
                res = num - Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(res));
                break;
            case 3:
                res = num * Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(res));
                break;
            case 4:
                res = num / Double.parseDouble(jTextField1.getText());
                jTextField1.setText(Double.toString(res));
                break;
            
        }
    }
    
    public void turnON()
    {
        jTextField1.setEnabled(true);
        
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        
        jButtonOne.setEnabled(true);
        jButtonTwo.setEnabled(true);
        jButtonThree.setEnabled(true);
        jButtonFour.setEnabled(true);
        jButtonFive.setEnabled(true);
        jButtonSix.setEnabled(true);
        jButtonSeven.setEnabled(true);
        jButtonEight.setEnabled(true);
        jButtonNine.setEnabled(true);
        jButtonZero.setEnabled(true);
        jButtonPlus.setEnabled(true);
        jButtonMinus.setEnabled(true);
        jButtonMultiplier.setEnabled(true);
        jButtonDivider.setEnabled(true);
        jButtonEqual.setEnabled(true);
        jButtonDot.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonClear.setEnabled(true);
        
    }
    
    public void turnOFF()
    {
        jTextField1.setEnabled(false);
        
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        
        jButtonOne.setEnabled(false);
        jButtonTwo.setEnabled(false);
        jButtonThree.setEnabled(false);
        jButtonFour.setEnabled(false);
        jButtonFive.setEnabled(false);
        jButtonSix.setEnabled(false);
        jButtonSeven.setEnabled(false);
        jButtonEight.setEnabled(false);
        jButtonNine.setEnabled(false);
        jButtonZero.setEnabled(false);
        jButtonPlus.setEnabled(false);
        jButtonMinus.setEnabled(false);
        jButtonMultiplier.setEnabled(false);
        jButtonDivider.setEnabled(false);
        jButtonEqual.setEnabled(false);
        jButtonDot.setEnabled(false);
        jButtonDelete.setEnabled(false);
        jButtonClear.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonMultiplier = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jButtonDivider = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackToHomeButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton5.setText("+");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton6.setText("+");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(274, 367));
        setResizable(false);
        setSize(new java.awt.Dimension(266, 352));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 245, 44));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jButtonDelete.setText("Del");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 94, -1, -1));

        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 94, 57, 31));

        jButtonSeven.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonSeven.setText("7");
        jButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSevenActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 57, 31));

        jButtonPlus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 94, 57, 31));

        jButtonEight.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonEight.setText("8");
        jButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEightActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 147, 57, 31));

        jButtonNine.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonNine.setText("9");
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNineActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 147, 57, 31));

        jButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 147, 57, 31));

        jButtonFive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonFive.setText("5");
        jButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 189, 57, 31));

        jButtonSix.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonSix.setText("6");
        jButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 189, 57, 31));

        jButtonMultiplier.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonMultiplier.setText("*");
        jButtonMultiplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplierActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultiplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 189, 57, 31));

        jButtonFour.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonFour.setText("4");
        jButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 57, 31));

        jButtonTwo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonTwo.setText("2");
        jButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 231, 57, 31));

        jButtonThree.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonThree.setText("3");
        jButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThreeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 231, 57, 31));

        jButtonDivider.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonDivider.setText("/");
        jButtonDivider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDivider, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 231, 57, 31));

        jButtonOne.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonOne.setText("1");
        jButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 57, 31));

        jButtonDot.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 273, 57, 31));

        jButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 273, 120, 31));

        jButtonZero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButtonZero.setText("0");
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, 57, 31));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 11, 152, 22));

        BackToHomeButton1.setBackground(new java.awt.Color(255, 255, 255));
        BackToHomeButton1.setFont(new java.awt.Font("Pristina", 1, 16)); // NOI18N
        BackToHomeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home4.png"))); // NOI18N
        BackToHomeButton1.setText("Back to Home");
        BackToHomeButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackToHomeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(BackToHomeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 193, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calc4.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 266, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        turnOFF();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEightActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_jButtonEightActionPerformed

    private void jButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNineActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_jButtonNineActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(jTextField1.getText());
        value = 2;
        jTextField1.setText("");
        jLabel1.setText(num + "-");
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_jButtonFiveActionPerformed

    private void jButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_jButtonSixActionPerformed

    private void jButtonMultiplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplierActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(jTextField1.getText());
        value = 3;
        jTextField1.setText("");
        jLabel1.setText(num + "*");
    }//GEN-LAST:event_jButtonMultiplierActionPerformed

    private void jButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_jButtonTwoActionPerformed

    private void jButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThreeActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_jButtonThreeActionPerformed

    private void jButtonDividerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividerActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(jTextField1.getText());
        value = 4;
        jTextField1.setText("");
        jLabel1.setText(num + "/");
    }//GEN-LAST:event_jButtonDividerActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
        if(!jTextField1.getText().contains("."))
        {
            jTextField1.setText(jTextField1.getText() + ".");
        }
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        arithmeticOperation();
        jLabel1.setText("");
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_jButtonOneActionPerformed

    private void jButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_jButtonFourActionPerformed

    private void jButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSevenActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_jButtonSevenActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble(jTextField1.getText());
        value = 1;
        jTextField1.setText("");
        jLabel1.setText(num + "+");
        
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        turnON();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int length = jTextField1.getText().length();
        int number = jTextField1.getText().length() - 1;
        String storedText;
        
        if(length > 0)
        {
            StringBuilder del = new StringBuilder(jTextField1.getText());
            del.deleteCharAt(number);
            storedText = del.toString();
            jTextField1.setText(storedText);
            
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void BackToHomeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_BackToHomeButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHomeButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDivider;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiplier;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
