/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agecalculate;

import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 19020
 */
public class DOB2Age extends javax.swing.JFrame {

    /**
     * Creates new form DOB2Age
     */
    public DOB2Age() {
        initComponents();
        //setTitle("project.in Age Calculator");
        //setSize(400,360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AgeCalcLabel = new javax.swing.JLabel();
        DateofBirthLabel = new javax.swing.JLabel();
        DateChooser1 = new com.toedter.calendar.JDateChooser();
        CalculateAgeButton = new javax.swing.JButton();
        YearsLabel = new javax.swing.JLabel();
        MonthsLabel = new javax.swing.JLabel();
        DaysLabel = new javax.swing.JLabel();
        YearsValueLabel = new javax.swing.JLabel();
        MonthsValueLabel = new javax.swing.JLabel();
        DaysValueLabel = new javax.swing.JLabel();
        ResetButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ACHelpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Age Calculator ");
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgeCalcLabel.setBackground(new java.awt.Color(255, 255, 255));
        AgeCalcLabel.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        AgeCalcLabel.setForeground(new java.awt.Color(204, 204, 204));
        AgeCalcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgeCalcLabel.setText("AGE CALCULATOR");
        jPanel1.add(AgeCalcLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 27, 260, 26));

        DateofBirthLabel.setBackground(new java.awt.Color(255, 255, 255));
        DateofBirthLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DateofBirthLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateofBirthLabel.setText("Date of Birth :");
        jPanel1.add(DateofBirthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 90, 107, 26));

        DateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        DateChooser1.setDateFormatString("dd/MM/yyyy");
        DateChooser1.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        jPanel1.add(DateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 90, 147, 26));

        CalculateAgeButton.setBackground(new java.awt.Color(102, 255, 102));
        CalculateAgeButton.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        CalculateAgeButton.setText("Calculate Age");
        CalculateAgeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CalculateAgeButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CalculateAgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateAgeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CalculateAgeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 146, 143, -1));

        YearsLabel.setBackground(new java.awt.Color(255, 255, 255));
        YearsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YearsLabel.setForeground(new java.awt.Color(255, 255, 255));
        YearsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearsLabel.setText("Years");
        jPanel1.add(YearsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 192, 77, 24));

        MonthsLabel.setBackground(new java.awt.Color(255, 255, 255));
        MonthsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MonthsLabel.setForeground(new java.awt.Color(255, 255, 255));
        MonthsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthsLabel.setText("Months");
        jPanel1.add(MonthsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 194, 90, -1));

        DaysLabel.setBackground(new java.awt.Color(255, 255, 255));
        DaysLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DaysLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaysLabel.setText("Days");
        jPanel1.add(DaysLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 188, 42, 33));

        YearsValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        YearsValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        YearsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearsValueLabel.setText("_____");
        jPanel1.add(YearsValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 231, 46, -1));

        MonthsValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MonthsValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        MonthsValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthsValueLabel.setText("______");
        jPanel1.add(MonthsValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 231, 49, -1));

        DaysValueLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DaysValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        DaysValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DaysValueLabel.setText("_____");
        jPanel1.add(DaysValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 231, 42, -1));

        ResetButton1.setBackground(new java.awt.Color(255, 255, 153));
        ResetButton1.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        ResetButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset4.png"))); // NOI18N
        ResetButton1.setText("RESET");
        ResetButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ResetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ResetButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 273, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home4.png"))); // NOI18N
        jButton1.setText("Back To Home");
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 324, 174, 30));

        ACHelpButton.setBackground(new java.awt.Color(51, 51, 255));
        ACHelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Help Icon 2.png"))); // NOI18N
        ACHelpButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ACHelpButton.setBorderPainted(false);
        ACHelpButton.setIconTextGap(0);
        ACHelpButton.setPreferredSize(new java.awt.Dimension(34, 34));
        ACHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACHelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ACHelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 19, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ACform2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateAgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateAgeButtonActionPerformed
        // TODO add your handling code here:
        String dateofbirth = ((JTextField)DateChooser1.getDateEditor().getUiComponent()).getText();
        System.out.println(""+dateofbirth);
        String dob[] = dateofbirth.split("/");
        
        System.out.println(""+dob[0]);
        System.out.println(""+dob[1]);
        System.out.println(""+dob[2]);
        
        int day = Integer.parseInt(dob[0]);
        int month = Integer.parseInt(dob[1]);
        int year = Integer.parseInt(dob[2]);
        
        LocalDate selectedDate = LocalDate.of(year,month,day);
        LocalDate currentDate = LocalDate.now();
        System.out.println(""+selectedDate);
        System.out.println(""+currentDate);
        
        int resultYear = Period.between(selectedDate, currentDate).getYears();
        int resultMonth = Period.between(selectedDate, currentDate).getMonths();
        int resultDays = Period.between(selectedDate, currentDate).getDays();
        
        
        YearsValueLabel.setText(""+resultYear);
        MonthsValueLabel.setText(""+resultMonth);
        DaysValueLabel.setText(""+resultDays);
        
    }//GEN-LAST:event_CalculateAgeButtonActionPerformed

    private void ResetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButton1ActionPerformed
        // TODO add your handling code here:
        
        DateChooser1. setCalendar(null);
        YearsValueLabel.setText("____");
        MonthsValueLabel.setText("____");
        DaysValueLabel.setText("____");
        
    }//GEN-LAST:event_ResetButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ACHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACHelpButtonActionPerformed
        // TODO add your handling code here:
        String line = "Step 1. Type Date of Birth in the textfield or select by clicking calendar button." + '\n' +
                      "Step 2. Click on the Calculate Age button for result." + '\n' +
                      "Step 3. Click on the Reset button to reset calculator screen." + '\n' +
                      "Step 4. Click on the Back to Home button to go back to Menu screen.";

        JOptionPane.showMessageDialog(null, line,"Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ACHelpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DOB2Age.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DOB2Age.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DOB2Age.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DOB2Age.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DOB2Age().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACHelpButton;
    private javax.swing.JLabel AgeCalcLabel;
    private javax.swing.JButton CalculateAgeButton;
    private com.toedter.calendar.JDateChooser DateChooser1;
    private javax.swing.JLabel DateofBirthLabel;
    private javax.swing.JLabel DaysLabel;
    private javax.swing.JLabel DaysValueLabel;
    private javax.swing.JLabel MonthsLabel;
    private javax.swing.JLabel MonthsValueLabel;
    private javax.swing.JButton ResetButton1;
    private javax.swing.JLabel YearsLabel;
    private javax.swing.JLabel YearsValueLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
