/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agecalculate;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class LeapYear extends javax.swing.JFrame {

    /**
     * Creates new form LeapYear
     */
    public LeapYear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LeapYearCheckerLabel1 = new javax.swing.JLabel();
        ChooseAnYearToCheckLabel1 = new javax.swing.JLabel();
        YearChooser1 = new com.toedter.calendar.JYearChooser();
        CheckButton1 = new javax.swing.JButton();
        LeapYearResultLabel1 = new javax.swing.JLabel();
        ResetButton2 = new javax.swing.JButton();
        LYHelpButton = new javax.swing.JButton();
        BackToHomeButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leap Year Checker");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(366, 344));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeapYearCheckerLabel1.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        LeapYearCheckerLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LeapYearCheckerLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeapYearCheckerLabel1.setText("Leap Year Checker");
        LeapYearCheckerLabel1.setToolTipText("");
        jPanel2.add(LeapYearCheckerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 31, 260, 38));

        ChooseAnYearToCheckLabel1.setFont(new java.awt.Font("Pristina", 1, 22)); // NOI18N
        ChooseAnYearToCheckLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ChooseAnYearToCheckLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChooseAnYearToCheckLabel1.setText("Choose an year to check");
        ChooseAnYearToCheckLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(ChooseAnYearToCheckLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 87, 260, 35));

        YearChooser1.setBackground(new java.awt.Color(255, 255, 255));
        YearChooser1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jPanel2.add(YearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 133, 79, 38));

        CheckButton1.setBackground(new java.awt.Color(102, 255, 153));
        CheckButton1.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        CheckButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check3.png"))); // NOI18N
        CheckButton1.setText("CHECK");
        CheckButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CheckButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(CheckButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 133, -1, 38));

        LeapYearResultLabel1.setFont(new java.awt.Font("Pristina", 1, 22)); // NOI18N
        LeapYearResultLabel1.setForeground(new java.awt.Color(255, 255, 255));
        LeapYearResultLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LeapYearResultLabel1.setText("Result will be showed here!!");
        jPanel2.add(LeapYearResultLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 329, 32));

        ResetButton2.setBackground(new java.awt.Color(255, 255, 153));
        ResetButton2.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        ResetButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset4.png"))); // NOI18N
        ResetButton2.setText("RESET");
        ResetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(ResetButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 232, 137, 31));

        LYHelpButton.setBackground(new java.awt.Color(51, 51, 255));
        LYHelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Help Icon 2.png"))); // NOI18N
        LYHelpButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LYHelpButton.setBorderPainted(false);
        LYHelpButton.setIconTextGap(0);
        LYHelpButton.setPreferredSize(new java.awt.Dimension(34, 34));
        LYHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LYHelpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LYHelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 31, -1, -1));

        BackToHomeButton1.setBackground(new java.awt.Color(204, 0, 51));
        BackToHomeButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        BackToHomeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home4.png"))); // NOI18N
        BackToHomeButton1.setText("Back to Home");
        BackToHomeButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BackToHomeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(BackToHomeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 274, 193, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stars3.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButton1ActionPerformed
        // TODO add your handling code here:
        int year = YearChooser1.getYear();
        
        if(year%400 == 0)
        {
          LeapYearResultLabel1.setText(""+ year + " is a leap year.");
          LeapYearResultLabel1.setForeground(Color.green);
        }
        else if(year%4 == 0 && year%100 !=0)
        {
          LeapYearResultLabel1.setText(""+ year + " is a leap year.");
          LeapYearResultLabel1.setForeground(Color.green);
        }
        else
        {
          LeapYearResultLabel1.setText(""+ year + " is not a leap year");
          LeapYearResultLabel1.setForeground(Color.red);
        }
    }//GEN-LAST:event_CheckButton1ActionPerformed

    private void ResetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButton2ActionPerformed
        // TODO add your handling code here:
        YearChooser1.setYear(2021);
        LeapYearResultLabel1.setText("Result will be showed here!!");
        LeapYearResultLabel1.setForeground(Color.black);
        
    }//GEN-LAST:event_ResetButton2ActionPerformed

    private void BackToHomeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_BackToHomeButton1ActionPerformed

    private void LYHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LYHelpButtonActionPerformed
        // TODO add your handling code here:
        String line = "Step 1. Select an year from the drop down menu." + '\n' +
                      "Step 2. Click on the Check button for result." + '\n' +
                      "Step 3. Click on the Reset button to reset calculator screen." + '\n' +
                      "Step 4. Click on the Back to Home button to go back to Menu screen.";

        JOptionPane.showMessageDialog(null, line,"Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LYHelpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeapYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeapYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeapYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeapYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeapYear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHomeButton1;
    private javax.swing.JButton CheckButton1;
    private javax.swing.JLabel ChooseAnYearToCheckLabel1;
    private javax.swing.JButton LYHelpButton;
    private javax.swing.JLabel LeapYearCheckerLabel1;
    private javax.swing.JLabel LeapYearResultLabel1;
    private javax.swing.JButton ResetButton2;
    private com.toedter.calendar.JYearChooser YearChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
