/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agecalculate;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgeCalculatorButton2 = new javax.swing.JButton();
        MultiCalculatorLabel1 = new javax.swing.JLabel();
        AgeCalculatorButton1 = new javax.swing.JButton();
        LeapYearCheckerButton1 = new javax.swing.JButton();
        BMICalculatorButton1 = new javax.swing.JButton();
        ExitButton1 = new javax.swing.JButton();
        CalculatorButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        AgeCalculatorButton2.setBackground(new java.awt.Color(51, 153, 255));
        AgeCalculatorButton2.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        AgeCalculatorButton2.setText("Age Calculator");
        AgeCalculatorButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AgeCalculatorButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeCalculatorButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multi Calculator");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MultiCalculatorLabel1.setBackground(new java.awt.Color(255, 255, 255));
        MultiCalculatorLabel1.setFont(new java.awt.Font("Pristina", 1, 28)); // NOI18N
        MultiCalculatorLabel1.setForeground(new java.awt.Color(255, 255, 255));
        MultiCalculatorLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MultiCalculatorLabel1.setText("Multi Calculator");
        MultiCalculatorLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(MultiCalculatorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 37, 218, 46));

        AgeCalculatorButton1.setBackground(new java.awt.Color(51, 153, 255));
        AgeCalculatorButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        AgeCalculatorButton1.setText("Age Calculator");
        AgeCalculatorButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AgeCalculatorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeCalculatorButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(AgeCalculatorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 175, -1));

        LeapYearCheckerButton1.setBackground(new java.awt.Color(255, 255, 153));
        LeapYearCheckerButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        LeapYearCheckerButton1.setText("Leap Year Checker");
        LeapYearCheckerButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LeapYearCheckerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeapYearCheckerButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(LeapYearCheckerButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 175, -1));

        BMICalculatorButton1.setBackground(new java.awt.Color(153, 255, 153));
        BMICalculatorButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        BMICalculatorButton1.setText("BMI Calculator");
        BMICalculatorButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BMICalculatorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMICalculatorButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(BMICalculatorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 175, -1));

        ExitButton1.setBackground(new java.awt.Color(255, 51, 51));
        ExitButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        ExitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit3.png"))); // NOI18N
        ExitButton1.setText("EXIT");
        ExitButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ExitButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 175, -1));

        CalculatorButton1.setBackground(new java.awt.Color(255, 204, 204));
        CalculatorButton1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        CalculatorButton1.setText("Calculator");
        CalculatorButton1.setPreferredSize(new java.awt.Dimension(133, 31));
        CalculatorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatorButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(CalculatorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, 30));

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CalcMenu1.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 366, 380));

        jPanel1.setPreferredSize(new java.awt.Dimension(366, 344));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgeCalculatorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeCalculatorButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new DOB2Age().setVisible(true);
    }//GEN-LAST:event_AgeCalculatorButton1ActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitButton1ActionPerformed

    private void LeapYearCheckerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeapYearCheckerButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new LeapYear().setVisible(true);
    }//GEN-LAST:event_LeapYearCheckerButton1ActionPerformed

    private void BMICalculatorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMICalculatorButton1ActionPerformed
       dispose();
       new BMI().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_BMICalculatorButton1ActionPerformed

    private void AgeCalculatorButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeCalculatorButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeCalculatorButton2ActionPerformed

    private void CalculatorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatorButton1ActionPerformed
        // TODO add your handling code here:
       dispose();
       new Calculator().setVisible(true);
    }//GEN-LAST:event_CalculatorButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgeCalculatorButton1;
    private javax.swing.JButton AgeCalculatorButton2;
    private javax.swing.JButton BMICalculatorButton1;
    private javax.swing.JButton CalculatorButton1;
    private javax.swing.JButton ExitButton1;
    private javax.swing.JButton LeapYearCheckerButton1;
    private javax.swing.JLabel MultiCalculatorLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
